Repository msarilar/EDEngineer, pull requests merged in 2018-12, with the labels that each got.

#464 Czech language update 24-11-2018
  EDEngineer/Resources/Data/localization.json
Labels: Czech, Localization

#465 Correct rarity value of Ship Flight Data
  EDEngineer/Resources/Data/entryData.json
Labels: RefData, bug

#467 Update blueprints.json
  EDEngineer/Resources/Data/blueprints.json
Labels: RefData, bug

#470 Update localization.json
  EDEngineer/Resources/Data/localization.json
Labels: Localization, Spanish

#476 Split both Guardian and Thargoid items into two subgroups (4 groups total)
  EDEngineer.Models/EntryData.cs
  EDEngineer.Models/Group.cs
  EDEngineer.Models/MaterialTrading/MaterialTrader.cs
  EDEngineer/Resources/Data/entryData.json
  EDEngineer/Resources/Data/localization.json
Labels: RefData, enhancement

#477 Fix to deal with Cargo events that contain no Inventory field
  EDEngineer/Utils/JournalEntryConverter.cs
Labels: bug
