Repository msarilar/EDEngineer, pull requests merged in 2021-08, with the labels that each got.

#643 Add Turkish Translate
  EDEngineer/Resources/Data/localization.json
Labels: Localization, Turkish

#648 Removed "Colonel Bris Dekker" from G5 FSDI EFICA
  EDEngineer/Resources/Data/blueprints.json
Labels: RefData

#649 Added Engineered DSS V1
  EDEngineer/Resources/Data/blueprints.json
Labels: enhancement, RefData
