Repository msarilar/EDEngineer, pull requests merged in 2021-06, with the labels that each got.

#599 Blueprints
  EDEngineer/Resources/Data/blueprints.json
  EDEngineer/Resources/Data/localization.json
  EDEngineer/Views/MainWindow.xaml
Labels: RefData, enhancement, odyssey

#601 Odyssey Events
  EDEngineer.Models/Blueprint.cs
  EDEngineer.Models/BlueprintCategory.cs
  EDEngineer.Models/EDEngineer.Models.csproj
  EDEngineer.Models/Equipment.cs
  EDEngineer.Models/Filters/CategoryFilter.cs
  EDEngineer.Models/Filters/CraftableFilter.cs
  EDEngineer.Models/Filters/EngineerFilter.cs
  EDEngineer.Models/Filters/GradeFilter.cs
  EDEngineer.Models/Filters/IgnoredFavoriteFilter.cs
  EDEngineer.Models/Filters/TypeFilter.cs
  EDEngineer.Models/JournalEvent.cs
  EDEngineer.Models/Operations/MaterialTradeOperation.cs
  EDEngineer.Models/Operations/UpgradeOperation.cs
  EDEngineer.Models/State/State.cs
  EDEngineer.Models/State/StateCargo.cs
  EDEngineer.Tests/MaterialTraderTests.cs
  EDEngineer.Tests/ReferenceDataIntegrityTests.cs
  EDEngineer/EDEngineer.csproj
  EDEngineer/Resources/Data/blueprints.json
  EDEngineer/Resources/Data/entryData.json
  EDEngineer/Resources/Data/equipment.json
  EDEngineer/Resources/Data/localization.json
  EDEngineer/Resources/Data/releaseNotes.json
  EDEngineer/Utils/BlueprintFilters.cs
  EDEngineer/Utils/JournalEntryConverter.cs
  EDEngineer/Utils/System/Helpers.cs
  EDEngineer/Views/CommanderViewModel.cs
  EDEngineer/Views/MainWindowViewModel.cs
  EDEngineer/Views/Notifications/NotificationSettingsViewModel.cs
Labels: enhancement, odyssey

#609 Improved source history
  EDEngineer.Models/JournalEvent.cs
  EDEngineer.Models/Operations/CargoOperation.cs
  EDEngineer.Models/Operations/CollectItemOperation.cs
  EDEngineer.Models/Operations/DataOperation.cs
  EDEngineer.Models/Operations/MaterialOperation.cs
  EDEngineer.Models/Operations/SystemUpdatedOperation.cs
  EDEngineer.Models/State/State.cs
  EDEngineer.Models/State/StateHistory.cs
  EDEngineer/Utils/JournalEntryConverter.cs
Labels: enhancement, odyssey

#611 Odyssey engineer blueprints
  EDEngineer/Resources/Data/blueprints.json
Labels: RefData, enhancement, odyssey

#619 Fix #616
  EDEngineer.Models/State/StateHistory.cs
Labels: enhancement

#627 entryData.json updated with data from ED Wiki
  EDEngineer/Resources/Data/entryData.json
Labels: RefData, odyssey
