Repository msarilar/EDEngineer, pull requests merged in 2021-07, with the labels that each got.

#632 Update localization.json French
  EDEngineer/Resources/Data/localization.json
Labels: French, Localization

#633 Updated entryData.json. Updated blueprint for Reload Speed.
  EDEngineer/Resources/Data/blueprints.json
  EDEngineer/Resources/Data/entryData.json
Labels: RefData, enhancement, odyssey

#635 Split 3 blueprints (Kinematic, Takada, Manticore). Added Odyssey consumables as materials
  EDEngineer/Resources/Data/blueprints.json
  EDEngineer/Resources/Data/entryData.json
Labels: RefData, odyssey

#640 Updated Blueprints for "accuracy", "headshot damage" and "weapon range
  EDEngineer/Resources/Data/blueprints.json
  EDEngineer/Resources/Data/entryData.json
Labels: enhancement, odyssey
