Repository msarilar/EDEngineer, pull requests merged in 2023-03, with the labels that each got.

#716 Spanish translation
  EDEngineer/Resources/Data/localization.json
Labels: Localization, Localization_Spanish

#717 Update blueprints.json
  EDEngineer/Resources/Data/blueprints.json
Labels: enhancement, RefData

#719 Added Thargoid Interdiction Telemetry
  EDEngineer/Resources/Data/entryData.json
Labels: enhancement, RefData

#722 Increased Ruthenium limit
  EDEngineer/Resources/Data/entryData.json
Labels: RefData

#730 Fix for #642
  EDEngineer/Resources/Data/blueprints.json
Labels: RefData
